on:
  workflow_call:
    inputs:
      cache_sha:
        type: string
        required: true

permissions:
  contents: write

env:
  NODE_VERSION: "20.17.0"
  PNPM_VERSION: "8.15.2"
  CESIUM_BASE_PATH: "/geoview/cesium/"

jobs:
  build:
    name: build-geoview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.push.repo.full_name || github.repository }}

      - uses: actions/setup-node@v3
        name: Install node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      # Run rush install and build on our code
      - name: Install Rush
        run: node common/scripts/install-run-rush.js install

      - name: Persist build output for other workflows
        uses: actions/cache@v3
        with:
          path: packages/geoview-core/dist
          key: dist-${{ inputs.cache_sha }}

      - name: Rush Build
        run: node common/scripts/install-run-rush.js build:core
