name: Publish to GitHub pages

on:
  workflow_call:
    inputs:
      cache_sha:
        type: string
        required: true
      folder:
        type: string
        required: true

jobs:
  deploy-to-pages:
    name: Deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get dist files
        uses: actions/cache@v4
        with:
          path: packages/geoview-core/dist
          key: dist-${{ inputs.cache_sha }}

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: packages/geoview-core/dist
          target-folder: ${{inputs.folder}}
          single-commit: true
